name: coastsat_stencila_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal
  - pip
  - pip:
    - arcp==0.2.1
    - attrs==25.3.0
    - certifi==2025.7.9
    - charset-normalizer==3.4.2
    - click==8.2.1
    - fastjsonschema==2.21.1
    - idna==3.10
    - Jinja2==3.1.6
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - jupyter_core==5.8.1
    - MarkupSafe==3.0.2
    - nbformat==5.10.4
    - platformdirs==4.3.8
    - python-dateutil==2.9.0.post0
    - referencing==0.36.2
    - requests==2.32.4
    - rocrate==0.14.0
    - rpds-py==0.26.0
    - six==1.17.0
    - traitlets==5.14.3
    - typing_extensions==4.14.1
    - urllib3==2.5.0