name: Generate Interface Crate

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-interface-crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Ensures full commit history is cloned

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: coastsat_stencila_env
          environment-file: environment.yaml
          python-version: "3.10"

      - name: Generate Interface Crate
        run: |
          conda run -n coastsat_stencila_env python LP_Crate/interface_crate.py 

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create release with CoastSat commit ID and timestamp
        run: |
          COMMIT_ID=$(git -C CoastSat rev-parse --short HEAD)
          TS=$(date +%Y%m%d%H%M%S)
          RELEASE_TAG="interface.crate-${COMMIT_ID}-${TS}"
          gh release create "$RELEASE_TAG" --title "Interface Crate (${COMMIT_ID} - ${TS})" --notes "Autogenerated from CoastSat commit ${COMMIT_ID} at ${TS}"

      - name: Zip interface crate
        run: (cd LP_Crate && zip -r ../interface-crate.zip interface.crate/)

      - name: Upload crate to release
        run: |
          COMMIT_ID=$(git -C CoastSat rev-parse --short HEAD)
          gh release upload "interface.crate-${COMMIT_ID}" interface-crate.zip --clobber