name: Generate Interface Crate

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-interface-crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo with submodules
        uses: actions/checkout@v4
        # with:
        #   submodules: recursive

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: coastsat_stencila_env
          environment-file: environment.yaml
          python-version: "3.10"

      - name: Check Python and pip packages
        run: |
          conda activate coastsat_stencila_env
          which python
          python -m pip list

      # - name: Generate Interface Crate
      #   run: |
      #     python LP_Crate/interface_crate.py