name: Generate Interface Crate

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-interface-crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Message
        run: echo "This worked"